workflows:
  android-workflow:
    name: Android Build
    environment:
      vars:
        VERSION_CODE: 1
        VERSION_NAME: 1.0.0
    scripts:
      - echo "Starting Android build..."
      - ./gradlew assembleDebug
    artifacts:
      - build/app/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - parsabhramabady615@gmail.com
